### ISSUE TITLE
Optimized Parallax

### ISSUE THREAD

**Issue by HarshKhandeparkar** [LBRYFoundation/lbryorg#15]
The parallax on this site is a custom one designed by me. After this site was published, I separately open-sourced the parallax code along w/ some optimizations.
![image](https://user-images.githubusercontent.com/34770591/94606143-ad052b80-02b7-11eb-987c-63f4df550b65.png)
This warning does not appear with the new parallax.

You might want to have a look at it [here](https://github.com/HarshKhandeparkar/shadowllax).

**Comment by Eniamza** [comment]
@HarshKhandeparkar Looks Good!

**Comment by Eniamza** [comment]
@HarshKhandeparkar  I am closing this issue as it's not a top priority for now.

**Comment by iamuditpatel** [comment]
@HarshKhandeparkar i try your new parallax effect code on my machine but it's broke the website maybe i did something wrong or the new code is not compatible with the website or something so it's great if you make pull request with your updated new parallax code.
![bug](https://user-images.githubusercontent.com/11346292/99530526-6edadd00-29c7-11eb-83d1-3290b1394654.PNG)

**Comment by HarshKhandeparkar** [comment]
I am pretty sure you made a mistake because the code hasn't changed at all. Sorry, but I don't have time to open a PR myself :)

**Comment by iamuditpatel** [comment]
for now i am closing this issue when you get time you welcome to make PR till we continue using old parallax code as the old parallax code look fine to me and work without any serious bug.

thank you
