### ISSUE TITLE
The Foundation Website not Maintained

### ISSUE THREAD

**Issue by ElectronEsq** [LBRYFoundation/lbryorg#20]
The Foundation website is not being maintained by the Foundation community.
I am not a member of this community but found outdated content while browsing the website, which I've submitted PRs for.

Ideally, there should be some sort of system in place to make sure the Foundation's website is maintained and always up-to-date. An outdated and poorly maintained website can harm [brand reputation](https://www.marketing91.com/brand-reputation/) and [brand authority](https://www.forbes.com/sites/forbescommunicationscouncil/2017/07/24/what-we-talk-about-when-we-talk-about-brand-authority)

**Comment by Coolguy3289** [comment]
The updates on the site where you're knowledgeable are appreciated! As things change in the foundation, we strive to update the site as soon as possible. Not all news propagates, and not everyone has the knowledge to edit the site, but if something needs changed, an issue being created is all that needs done, and our wonderful team that put this together will usually get it handled within a day or two.
