### ISSUE TITLE
Change Instructions from !addrole/!delrole/!roles

### ISSUE THREAD

**Issue by Coolguy3289** [LBRYFoundation/lbryorg#21]
With the removal of Wunderbot's RoleSetter feature in favor of Warship's Reaction Role utility, information on the site that directs users to use commands such as !addrole <role>, etc. are no longer applicable. They should instead direct users to the #hiveroles channel to react with the hive's emoji as dictated on the message posted there.

**Comment by iamuditpatel** [comment]
@Coolguy3289  working on it to fix it

**Comment by iamuditpatel** [comment]
@Coolguy3289 #22 i updated the role info as per your request 👍
