### ISSUE TITLE
styling issues

### ISSUE THREAD

**Issue by tzarebczan** [LBRYFoundation/lbryorg#24]
![image](https://user-images.githubusercontent.com/8120721/105202953-855cfc00-5b10-11eb-813e-12630a088cc5.png)

**Comment by Eniamza** [comment]
@tzarebczan 
The styling seems to be working on my side. 
![image](https://user-images.githubusercontent.com/65225917/105519507-b4878f00-5d03-11eb-9bbd-07a00d020c1f.png)
