### ISSUE TITLE
Add OpenGraph and other metadata

### ISSUE THREAD

**Issue by kauffj** [LBRYFoundation/lbryorg#3]
Page titles, og:description, og:image, possibly twitter specific ones, and a general audit of all header metadata that could or should be included (you can check what we include at lbry.com).

**Comment by iamuditpatel** [comment]
thanks for opening this issue we started working on this to fix it

**Comment by iamuditpatel** [comment]
@kauffj Add OpenGraph and other metadata Issue is FIX NOW 👍    https://github.com/LBRYFoundation/lbryorg/commit/d00ac19ad366c0649be3ee690d60b3a02e34b3e9

**Comment by iamuditpatel** [comment]
you can test the website metadata here :) it's working for google, facebook and twitter

https://metatags.io/

thank you
