### ISSUE TITLE
Markdown needs some makeup.

### ISSUE THREAD

**Issue by Eniamza** [LBRYFoundation/lbryorg#7]
The current markdown in most pages seems too basic which is affecting the appearance of the site.

**Comment by iamuditpatel** [comment]
markdown is very basic by it's nature so it's don't allow us to do more styling like what HTML & CSS offer but it's great if you make pull request with style changes you want in the website.

**Comment by iamuditpatel** [comment]
for now we close this issue and you are welcome to make PR if you want to make any style change in the website. hope your PR makes the website design more great

thank you
